### ISSUE TITLE
compiling on raspbian stretch

### ISSUE THREAD

**Issue by jsarcand** [dpapavas/alsaloudness#3]
`loudness_pcm.c:31:19: fatal error: fftw3.h: Aucun fichier ou dossier de ce type
 #include <fftw3.h>
                   ^
compilation terminated.`

compilation failed because it can't find the fournier transform library, which is installed (libfftw3-3 version 3.3.5-3)

is it compatible?

**Comment by dpapavas** [comment]
Try `sudo apt install libfftw3-dev`.

**Comment by jsarcand** [comment]
that did the trick!!  thanks 👍
