### ISSUE TITLE
feature request: plugin version

### ISSUE THREAD

**Issue by magnetophon** [dpapavas/alsaloudness#7]
This would be great to have in the monitoring bus of a DAW like ardour.
For that it would have to be a plugin, either LV2 or LADSPA.

**Comment by dpapavas** [comment]
I will interpret your rather terse observation as a request to turn `alsaloudness` into a LV2/LADSPA plugin.  I have been asked to do this before, but shortness of time and the fact that I don't have any experience with DAW-related work led me to turn it down.

Free time is a little better at the moment though, so I'll leave this issue open and look into it, as soon as I get a chance.  If the amount of work required is not prohibitively high, I'll give it a shot, although I can't make any promises.

Out of curiosity, but also to give me an idea about how a loudness compensation plugin might be used, how exactly would it be useful with a DAW?

**Comment by magnetophon** [comment]
The request is in the title, sorry for the terseness!  :)

Thanks for considering.

I would like to the plugin as intended; to compensate for the ear's lower sensitivity to the extremes of the audible spectrum when listening at low volumes. 
I tend to mix at low volumes to counter ear-fatigue, and I really struggle not to make my mixes too bass-heavy. For years now, I am aware of this while mixing, but it's still a trap I fall into to a certain extent.    [Slowly](https://magnetophon.nl/sounds/UpsilonAcruxOld.mp3) [getting](https://magnetophon.nl/sounds/Lecheburre/Demokrati.mp3) [better](https://magnetophon.nl/sounds/SomaAge/SomaAge_BridcharBlues_big.mp4) though! ;)
I hope your software will let me follow my gut instinct to mix bass-heavy, without it negatively affecting the end result.

The reason a plugin would be nice is twofold:
- I regularly record on rented or borrowed hardware and then mix on my own. It would simplify the setup if the loudness compensation is separate from the hardware. 
- Ardour has a handy [monitor section](https://manual.ardour.org/ardours-interface/the-monitor-section/), where a plugin it would fit perfectly, UX wise and conceptually.

I hope that clarifies things, let me know if you have any questions!

**Comment by dpapavas** [comment]
Thank you for your detailed description of the use-case (and nice work, by the way!)  Sorry for the long delay in replying;  I wanted to have something concrete to say and it took some time before I could find some spare time to look into this.  You can find an update in [this discussion thread](https://github.com/sadko4u/lsp-plugins/issues/81#issuecomment-651117501), which you're probably monitoring already.  I should be back soon with more developments.

**Comment by magnetophon** [comment]
> which you're probably monitoring already. 

Yup, just read your reply there. Great to hear there are now 2 people working on this!  :rocket:

Maybe you could join forces: you already have the dsp working, @sadko4u has lots of experience with lv2  ( and with build systems, for that matter, but you very well might have that too.)

**Comment by sadko4u** [comment]
@magnetophon 

Building plugins for LSP is pretty easy: you just define plugin metadata, some plugin classes and combine them together.
There is no problem to implement algorithmic-approximated and table-approximated solutions.
The main problem currently is just generating weight for each frequency in the FFT frame and put the processor to the plugin's audio processing callback routine. And we'll get not only LV2 but also VST and LADSPA plugins, too.

**Comment by magnetophon** [comment]
@sadko4u Anything is easy when you are good at it!  :)

**Comment by dpapavas** [comment]
I'm not sure whether the messages above are meant for this feature request, or whether they inadvertantly spilled over from the other discussion, but am I to take it that turning `alsaloudness` into a plugin won't be necessary anymore?  It'd be a pity for a weekend's work to go to waste, but, on the other hand, it'd be worse to do more work that nobody is going to use (and further complicate the codebase in the process).

I'm not sure how LSP works exactly, but if you deem that having the plugin there would be preferable, I would have to defer to your judgement, since I've no experience on the matter.

**Comment by magnetophon** [comment]
@dpapavas Since lsp now has the plugin, I guess we can close this issue.
Thanks for listening, and sorry for the wasted weekend!
